version: '2'

volumes:
    logs:
        driver: local

services:
    db:
        container_name: emcash_db
        image: mysql:5.7
        volumes:
            - ./db-fixtures:/db-fixtures:rw
            - ./db-storage:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=root #not working
    api:
        container_name: emcash_api
        image: yiisoftware/yii2-php:7.1-apache
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app:delegated
        ports:
            - 8000:80
